name: findar
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  group_button: ^5.3.4
  main_button: ^0.0.19
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  http: ^1.1.0
  image_picker: ^1.0.7
  sqflite: ^2.0.0
  path: ^1.8.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

  dio: ^5.0.10
  retrofit: ^4.4.1
  json_annotation: ^4.7.0
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  retrofit_generator: ^10.1.0
  build_runner: ^2.10.4
  json_serializable: ^6.10.0
    

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
